name: Terraform

on:
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'apply or destroy'
        required: true
        default: 'plan'
      environment:
        description: "Select environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - test

permissions:
  contents: read
  id-token: write

jobs:
  dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495680546469:role/github-action-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Validate
        run: terraform validate

      - name: Security Scan
        run: |
          pip install checkov
          checkov -d .

      - name: Terraform Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: terraform plan #-input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -input=false
  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254317103086:role/github-action-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd environments/test && terraform init

      - name: Terraform Format
        run: cd environments/test && terraform fmt -check

      - name: Terraform Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: cd environments/test && terraform plan #-input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: cd environments/test && terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: cd environments/test && terraform destroy -auto-approve -input=false
