name: Terraform_Security_Policy_Check

on:
  pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  terraform-security:
    name: Terraform + Security + Policy Check
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      TF_VERSION: "1.14.8"
      ENV: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. AWS OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495680546469:role/github-action-role
          aws-region: us-east-1

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 4. Install OPA + Conftest
      - name: Install OPA
        uses: open-policy-agent/setup-opa@v2

      - name: Setup Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.67.1/conftest_0.67.1_Darwin_x86_64.tar.gz
          tar xzf conftest_0.67.1_Darwin_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: environments/${{ env.ENV }}

      # 6. Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # 7. OPA Unit Tests (policy validation)
      - name: Run OPA Tests
        run: opa test policies/ -v

      # 8. Security Scan (Checkov)
      - name: Run Checkov Scan
        run: |
          pip install checkov
          checkov -d .  --skip-path .github/workflows/terraform.yml

      # 9. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        working-directory: environments/${{ env.ENV }}

      # 10. Convert Plan to JSON
      - name: Convert Plan
        run: terraform show -json tfplan.binary > tfplan.json
        working-directory: environments/${{ env.ENV }}

      # 11. Conftest Policy Enforcement
      - name: Run Conftest
        run: conftest test environments/${{ env.ENV }}/tfplan.json -p policies/

      # 12. Apply (manual trigger only)
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: ./scripts/deploy.sh ${{ env.ENV }}
        #working-directory: environments/${{ env.ENV }}

      # 13. Destroy (manual trigger only)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: ./scripts/deploy.sh ${{ env.ENV }}
        #working-directory: environments/${{ env.ENV }}