name: Terraform

on:
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'apply or destroy'
        required: true
        default: 'plan'

permissions:
  contents: read
  id-token: write

jobs:
  dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254317103086:role/github-action-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd environments/dev && terraform init

      - name: Terraform Format
        run: cd environments/dev && terraform fmt -check

      - name: Terraform Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: cd environments/dev && terraform plan #-input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: cd environments/dev && terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: cd environments/dev && terraform destroy -auto-approve -input=false
  test:
    needs: dev
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254317103086:role/github-action-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd environments/test && terraform init

      - name: Terraform Format
        run: cd environments/test && terraform fmt -check

      - name: Terraform Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: cd environments/test && terraform plan #-input=false

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: cd environments/test && terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: cd environments/test && terraform destroy -auto-approve -input=false
